"""empty message

Revision ID: 2c950c0a31bc
Revises: dfbda468d223
Create Date: 2022-08-05 15:09:22.199101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c950c0a31bc'
down_revision = 'dfbda468d223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battling',
    sa.Column('battling_id', sa.Integer(), nullable=True),
    sa.Column('battler_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['battler_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['battling_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battling')
    # ### end Alembic commands ###
